version: '3'

services:
  dropbox-client:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
    container_name: dropbox-client
    ports:
      - "8000:8000"
    volumes:
      - ../../client/server:/app/server
      - ../../client/db:/app/db
      - ../../client/scripts:/app/scripts
      - ../../client/requirements.txt:/app/requirements.txt
      - ../../client/config.py:/app/config.py
      - dropbox-data:/app/my_dropbox
      - db-data:/app/data
      - chunk-data:/app/tmp/chunk
    environment:
      - PYTHONPATH=/app
      - APP_DIR=/app
      - SYNC_DIR=/app/my_dropbox
      - CHUNK_DIR=/app/tmp/chunk
      - DATABASE_URL=sqlite:///./data/dropbox.db
      - DB_FILE_PATH=/app/data/dropbox.db
      - DB_POOL_SIZE=20
      - DB_MAX_OVERFLOW=10
      - DB_POOL_TIMEOUT=30
      - DB_POOL_RECYCLE=3600
      - CHUNK_SIZE=5242880
      - API_HOST=0.0.0.0
      - API_PORT=8000
    restart: unless-stopped

volumes:
  dropbox-data:
    driver: local
  db-data:
    driver: local
  chunk-data:
    driver: local
